### ISSUE TITLE
Possible release?

### ISSUE THREAD

**Issue by gavinmdouglas** [sim82/papara_nt#5]
Hi there,

I'm interested in making a conda recipe for PaPaRa (see discussion here: https://groups.google.com/forum/#!category-topic/phylogenetic-placement/cdUsCs5izr8). Is there a compressed folder that containing the source code that I could link to? If not, would it be possible to make a release of the current developmental version on github? I can also fork the repo and make a release, but I thought it would be better to be part of the official repo.

Thanks!

Gavin

**Comment by sim82** [comment]
Hi Gavin,
since I've been out of academia for quite some time now there has not been any new development on papara since the last release (2.5). The official source package is available from the HITS website (https://sco.h-its.org/exelixis/resource/download/software/papara_nt-2.5-source.tar.gz). The code should be equivalent to the corresponding github branch (https://github.com/sim82/papara_nt/tree/release/2.5)

Regards Simon

**Comment by gavinmdouglas** [comment]
Ok thanks for the clarification Simon!
